site_name: Apuntes
site_author: 'Jorge Pastor'
site_url: 'https://jorgepastorr.github.io/apuntes/'

repo_name: 'jorgepastorr/apuntes'
repo_url: https://github.com/jorgepastorr/apuntes/

theme:
    name: 'material'
    palette:
        primary: 'deep purple'
        accent: 'deep purple'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'



markdown_extensions:
    - admonition
    - codehilite
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
    - pymdownx.superfences


